version: '3.8'

services:
  web:
    build: .
    container_name: webapp
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

    restart: always

volumes:
  dbdata:
